guest_name = "Harry Styles"
party_name = "50th Anniversary"
date = "April 4th, 2045"
time = "7 pm"
host_name = "Val"

puts"Dear #{guest_name}" 
puts "You have been invited to my #{party_name}" 
puts "It will take place at my house #{date} at #{time}" 
puts "With all the love, #{host_name}" 
