guest_name = "Harry Styles"
party_name = "50th Anniversary"
date = "April 4th, 2045"
time = "7 pm"
host_name = "Val"

"Dear #{guest_name}" 
"You have been invited to my #{party_name}" 
"It will take place at my house #{date} at #{time}" 
"With all the love, #{host_name}" 
